version: '2'

services:
  elasticsearch:
    build:
      context: elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:rodo
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  order-service:
    container_name: order-service
    image: order-service:v2.0
    ports:
      - 8080:8080
    networks:
      - elk
    depends_on:
      - user-service
      - product-service
      - logistics-service

  user-service:
    container_name: user-service
    image: user-service:v1.0
    ports:
      - 8081:8081
    networks:
      - elk

  product-service:
    container_name: product-service
    image: product-service:v1.0
    ports:
      - 8083:8083
    networks:
      - elk
    volumes:
      - "/tmp:/sells"

  logistics-service:
    container_name: logistics-service
    image: logistics-service:v1.0
    ports:
      - 8082:8082
    networks:
      - elk

  zipkin-server:
    build:
      context: logistics-service
    ports:
      - 9411:9411
    networks:
      - elk

networks:
  elk:
    driver: bridge
