server:
  port: 8081
  context-path: /user-service
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://zipkin-server:9411
  sleuth:
    sampler:
      percentage: 1.0
logging:
  path: ./build/log
