server:
  port: 9411
spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
  zipkin:
    storage:
      type: elasticsearch
      StorageComponent: elasticsearch
      elasticsearch:
        cluster: docker-cluster
        max-requests: 30
        index: zipkin
        index-shards: 3
        index-replicas: 1
        hosts: elasticsearch:9200

