server:
  port: 8083
  context-path: /product-service
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://zipkin-server:9411
  sleuth:
    sampler:
      percentage: 1.0
logging:
  file: /log/product-service.log
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
